#!/usr/bin/python
import subprocess
import sys

# Populate these options if you want to set specific options for the printer. E.g. duplexing installed, etc.
printerOptions = { "OutputMode":"Enhanced", "Duplex":"DuplexNoTumble", "XRXColor":"Automatic", "XRXGrayline":"Composite", "XRXMismatch":"Scale", "XRXJobType":"Normal",  }

cmd = [ '/usr/sbin/lpadmin', '-x', 'XeroxPhaser8860' ]
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(lpadminxOut, lpadminxErr) = proc.communicate()

# Install the printer
cmd = [ '/usr/sbin/lpadmin',
        '-p', 'XeroxPhaser8860',
        '-L', 'Eco Office',
        '-D', 'Xerox Phaser 8860',
        '-v', 'lpd://192.168.181.154',
        '-P', "/Library/Printers/PPDs/Contents/Resources/Xerox Phaser 8860.gz",
        '-E',
        '-o', 'printer-is-shared=false',
        '-o', 'printer-error-policy=abort-job' ]

for option in printerOptions.keys():
    cmd.append("-o")
    cmd.append(str(option) + "=" +  str(printerOptions[option]))

proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(lpadminOut, lpadminErr) = proc.communicate()

if lpadminErr:
    print "Error: %s" % lpadminErr
    sys.exit(1)
print "Results: %s" % lpadminOut    
sys.exit(0)